name: 03 Multiple Events

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    issues:
        types: [opened, labelled]

jobs:
    display-event:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Triggered by ${{ github.event_name }}"