name: 04 Manual Deployment

on:
    workflow_dispatch:
        inputs:
            environment:
                description: Deployment environment
                required: true
                type: choice
                options:
                    - development
                    - staging
                    - production
            version:
                description: Application version
                required: true
                type: string
            dry_run:
                description: Perform dry run
                type: boolean
                default: true


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Environment: ${{ inputs.environment }}"
                echo "Version: ${{inputs.version }}"
                echo "Dry run: ${{ inputs.dry_run }}"