name: 08 matrix

on:
    workflow_dispatch:

jobs:
    matrix:
        strategy:
            matrix:
                version: [10,20]
                os: [ubuntu-latest, windows-latest]
                include:
                    - version: 14
                      os: ubuntu-latest
                    - version: 20
                      os: windows-latest
                      
        runs-on: ${{ matrix.os }}

        steps:
            - name: run matrix
              run: |
                echo "Install version: ${{ matrix.version }} in OS: ${{ matrix.os }}"
