name: 09 workflow commands

on:
    workflow-dispatch:

jobs:
    workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Workflow commands
              id: details
              run: |
                echo: "::add-mast::SensitiveDemoValue"