name: 10 workflow contexts

on:
    workflow_dispatch:

jobs:
    workflow-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: workflow-contexts
              run: |
                echo "Actor: ${{ github.actor }}"
                echo "Runner OS: ${{ runner.os }}"
                exit 1

            - name: Job-Success
              if: job.status == 'success'
              run: |
                echo "Job status: ${{ job.status }}"
            
            - name: Job-Failed
              if: job.status == 'failure'
              run: |
                echo "Job status: ${{ job.status }}"