name: 12 secret workflow

on:
    push:

jobs:
    repo-secret:
        runs-on: ubuntu-latest
        steps:
            - name: repo-secret
              run: |
                echo "Repo secret length: ${#repo_secret}"
              env:
                repo_secret: ${{ secrets.API_SECRET }}
    environment-secret:
        runs-on: ubuntu-latest
        environment: app_secret
        steps:
            - name: env-secret
              run: |
                echo "env secret length: ${#production}"
              env:
                production: ${{ secrets.AUTH_SECRET }}
            