name: 12 secret workflow

on:
    push:

jobs:
    repo-secret:
        runs-on: ubuntu-latest
        steps:
            - name: repo-secret
              run: |
                echo "Repo secret length: ${#repo_secret}"
              env:
                repo_secret: ${{ secrets.API_SECRET }}
