name: 12 secret workflow

on:
    push:

jobs:
    repo-secret:
        runs-on: ubuntu-latest
        steps:
            - name: repo-secret
              run: |
                echo "Secret: ${{ secrets.API_SECRET }}"