name: 16 publish github package

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22
                registry-url: https://npm.pkg.github.com
                scope: '@twinkalkumar'

            - name: Show npm config
              run: npm config list

            - name: Check token exists
              run: |
                if [ -z "$NODE_AUTH_TOKEN" ]; then
                echo "Token missing"
                exit 1
                else
                echo "Token available"
                fi
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Install dependencies
              run: npm install

            - name: Publish package
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}